[package]
name = "subfont-core"
version = "0.1.2"
edition = "2021"

[dependencies]
walkdir = "2.5.0"
anyhow = "1"
ttf-parser = "0.21"
rayon = "1.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
unicode-normalization = "0.1.23"
md5 = "0.7.0"
fontcull = { version = "2.0.1", features = [
    "woff2",
    "static-analysis",
] }

[[bin]]
name = "subfont-core"
path = "src/main.rs"
